In [2]:
import pandas as pd



In [3]:
df=pd.read_csv('/content/drive/MyDrive/Data set/student .csv')
df.head()


Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [4]:
df.tail()

Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

In [5]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB
None


In [6]:
(df.describe())

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [7]:
feature_columns=['Reading','Writing']
label_columns=['Math']
X=df[feature_columns]
y=df[label_columns]
print("Features shape:",X.shape)
print("Labels shape:",y.shape)

Features shape: (1000, 2)
Labels shape: (1000, 1)


In [8]:
import numpy as np
#Number of features and examples
d=2
n=1000
#Reshape X to (d*n) and create W
X=X.T
#initialize w as a random vector of shape
W=np.random.randn(d,1)
Y_computed=np.dot(W.T,X)
print("Weight Vector (w):\n",W)
print("Y_computed:\n",Y_computed.T)


Weight Vector (w):
 [[-2.54861921]
 [-0.39953858]]
Y_computed:
 [[-198.47703637]
 [-235.20493325]
 [-235.0535455 ]
 [-243.0989417 ]
 [-187.88302097]
 [-248.04479237]
 [-247.24571521]
 [-138.71480356]
 [-230.75538424]
 [-229.55676851]
 [-201.42519416]
 [-260.23696208]
 [-130.11848104]
 [-229.55676851]
 [-206.37104482]
 [-130.51801961]
 [-211.31689549]
 [-139.91341929]
 [-263.3365076 ]
 [-219.91321801]
 [-168.99545854]
 [-194.57841369]
 [-213.46597612]
 [-152.105589  ]
 [-252.7424922 ]
 [-262.53743045]
 [-195.37749084]
 [-217.51598655]
 [-229.55676851]
 [-240.15078392]
 [-225.80953358]
 [-262.53743045]
 [-217.3645988 ]
 [-201.82473273]
 [-122.872162  ]
 [-181.83531766]
 [-155.05374678]
 [-227.80722646]
 [-215.7664445 ]
 [-130.51801961]
 [-256.09018856]
 [-224.21137927]
 [-182.38624398]
 [-146.05788568]
 [-202.07288356]
 [-213.46597612]
 [-155.05374678]
 [-219.36229169]
 [-294.81577832]
 [-220.96044599]
 [-294.81577832]
 [-261.58696555]
 [-237.60216471]
 [-149.15743121]
 [-147.40788916]
 

In [9]:
import numpy as np
X = np.random.randn(1000, 2)
Y = np.random.rand(1000, 1)
def simple_train_test_split(X, Y, test_size=0.2):
    split_index = int(X.shape[0] * (1 - test_size))
    X_train, X_test = X[:split_index], X[split_index:]
    Y_train, Y_test = Y[:split_index], Y[split_index:]
    return X_train, X_test, Y_train, Y_test
X_train, X_test, Y_train, Y_test = simple_train_test_split(X, Y, test_size=0.2)
print("Shapes of the datasets:")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

Shapes of the datasets:
X_train shape: (800, 2)
X_test shape: (200, 2)
Y_train shape: (800, 1)
Y_test shape: (200, 1)


In [10]:
import numpy as np
import matplotlib.pyplot as plt

def gradient_descent(X, Y, W, learning_rate, num_iterations):
    m = X.shape[0]
    for i in range(num_iterations):
        predictions = np.dot(X, W)
        error = predictions - Y
        gradient = np.dot(X.T, error) / m
        W = W - learning_rate * gradient
    return W

def simple_train_test_split(X, Y, test_size=0.2):
    split_index = int(X.shape[0] * (1 - test_size))
    X_train, X_test = X[:split_index], X[split_index:]
    Y_train, Y_test = Y[:split_index], Y[split_index:]
    return X_train, X_test, Y_train, Y_test

def model_pipeline(data, test_size=0.2, learning_rate=0.01, iterations=1000):
    X, Y = data[:, :-1], data[:, -1].reshape(-1, 1)
    X_train, X_test, Y_train, Y_test = simple_train_test_split(X, Y, test_size=test_size)
    X_train = (X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)
    X_test = (X_test - np.mean(X_test, axis=0)) / np.std(X_test, axis=0)
    d = X_train.shape[1]
    W = np.random.rand(d, 1)
    W = gradient_descent(X_train, Y_train, W, learning_rate, iterations)
    Y_pred = np.dot(X_test, W)
    rmse = np.sqrt(np.mean((Y_test - Y_pred) ** 2))
    ss_total = np.sum((Y_test - np.mean(Y_test)) ** 2)
    ss_residual = np.sum((Y_test - Y_pred) ** 2)
    r2 = 1 - (ss_residual / ss_total)
    print("Root Mean Squared Error (RMSE):", rmse)
    print("R^2 Score:", r2)
    return W

data = np.random.rand(1000, 3)
W_learned = model_pipeline(data, test_size=0.2, learning_rate=0.01, iterations=1000)
print("Learned Weights:\n", W_learned)

Root Mean Squared Error (RMSE): 0.5891868241563394
R^2 Score: -3.138624663705026
Learned Weights:
 [[ 0.01034686]
 [-0.00033761]]
